name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12.0.1
          - 12.4

    steps:
    - uses: actions/checkout@master
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Run unit tests
      run:  xcodebuild clean test -workspace Logo/Logo.xcworkspace -scheme Logo | xcpretty && exit ${PIPESTATUS[0]}
